### ISSUE TITLE
Chat persistant accross domains

### ISSUE THREAD

**Issue by ghpranav** [fireship-io/gun-chat#3]
I cloned the repo & re-deployed the code to Github Pages over here:
https://ghpranav.github.io/gun-chat/

I was expecting the chat page to be empty since it's a different domain. But when I created a new user & logged in for testing, it is syncing all the texts from your domain ( https://gun-chat-dapp.web.app/ ) as well. Is this the expected behavior? If yes, then how can I deploy a separate chat app where messages are synced only with those who use my domain?

**Comment by tisaconundrum2** [comment]
I don't know if it helps, but Fireship does talk about the use of a Node that keeps all that data. In his video it is briefly discussed at 2:52. I have a feeling that because you didn't change the "name" of the node, you're essentially seeing all of his data.

**Comment by ghpranav** [comment]
Yup, that made sense. Thanks!

**Comment by eikaramba** [comment]
what i find weird however is that there is no server in the whole repository here. https://github.com/fireship-io/gun-chat/blob/main/src/Chat.svelte#L9 just uses the default GUN Server it seems. can anyone point me why this repo here cloned would use a certain server and where in the code this is specified?
